### ISSUE TITLE
Theme is broken currently

### ISSUE THREAD

**Issue by irfanshaik11** [codedthemes/mantis-free-react-admin-template#26]
**Describe the bug**

I get this error when running the theme. Steps to reproduce: fork the repo and launch the theme with no changes.

TypeError: Cannot read properties of undefined (reading 'getState')

This occurs on all versions of MUI themes. Both in this repository and the others (even the purchased full versions).

**Comment by phoenixcoded20** [comment]
This is not reproducible with the steps you mention. can you provide some more details?
