### ISSUE TITLE
Taking off the localhost:300/free Part and replace it with the app name 

### ISSUE THREAD

**Issue by PatriciaCollinz** [codedthemes/mantis-free-react-admin-template#27]
Like the title descirbes that's where I'm stuck, I've tried going where <BrowserRouter basename="/free"> is and remplaced it with  <BrowserRouter basename="/">and still get the same URL, btw I'm using the free version 1.1.2.

PS: to clarify the issue is not in the browser per say, it's in vs code when I type npm start, the automatic url it goes to is localhost:3000/free so when it opens up in the browser obviously there's nothing bc I changed the path so I have to delete free from the link and leave it at 3000, that's my issue... I'd like it to generate the path localhost:3000 and automaitucally show that in the browser.

Thank you in advance

**Comment by kartikchhipa** [comment]
In the package.json remove the "homepage" key

**Comment by phoenixcoded20** [comment]
> In the package.json remove the "homepage" key

This should resolve issue. Please reopen if not.
