### ISSUE TITLE
Dropdown menu on the sidebar options

### ISSUE THREAD

**Issue by TheoCathy** [codedthemes/mantis-free-react-admin-template#30]
**Is your feature request related to a problem? Please describe.**
it will be alot easier if users can have a templete for a drop down menu options

**Describe the solution you'd like**
To have one of the side bar menu options to have a dropdown menu option

**Describe alternatives you've considered**
Manually creating a dropdown which serves the purpose but it will be alot more easier if it was included in this project

**Additional context**

**Comment by phoenixcoded20** [comment]
Having a drop down in side bar can be seen in premium version. https://mantisdashboard.io/dashboard/analytics
